- name: "DEBUG:: teardown of resource group {{ res_grp }}"
  debug:
    msg: "The current server obj is {{ res_grp }}"

- name: "Including credentials of current resource {{ res_grp['resource_group_name'] }}"
  include_vars: "roles/aws/vars/{{ res_grp['assoc_creds'] | default(res_grp['credentials']) }}.yml"
  no_log: true 

- name: "Parsing topology output file "
  output_parser:
    output_file: "{{ topo_output_file }}.yaml"
  register: topo_output

#- name: "teardown AWS ec2 resources"
#  include: teardown_res_defs.yml
#  when: state == "absent"

# patch for res_type to type translation 
- name: "Add attribute res_type to res_grp resource_definitions"
  set_fact:
    resource_definitions: "{{ res_grp['res_defs'] | default(res_grp['resource_definitions']) | duplicateattr('type', 'res_type') }}"

- name: "teardown of ec2 resource definitions of current group"
  include: teardown_aws_ec2.yml res_def={{ res_item.0 }} tp_out={{ res_item.1 }} res_grp_name={{ res_item.2 }}
  when: res_item.0['res_type'] == "aws_ec2"
  with_nested:
    - "{{ resource_definitions }}"
    - "{{ topo_output['output']['content']['aws_ec2_res'] }}"
    - ["{{ res_grp['resource_group_name']  }}"]
  loop_control:
    loop_var: res_item

- name: "teardown of s3 resource def of current group"
  include: teardown_aws_s3.yml res_def={{ res_item.0 }} res_grp_name={{ res_item.1 }}
  when: res_item.0['res_type'] == "aws_s3"
  with_nested:
    - "{{ resource_definitions }}"
    - ["{{ res_grp['resource_group_name']  }}"]
  loop_control:
    loop_var: res_item

- name: "teardown of aws_ec2_key resource def of current group"
  include: teardown_aws_ec2_key.yml res_def={{ res_item.0 }} res_grp_name={{ res_item.1 }}
  when: res_item.0['res_type'] == "aws_ec2_key"
  with_nested:
    - "{{ resource_definitions }}"
    - ["{{ res_grp['resource_group_name']  }}"]
  loop_control:
    loop_var: res_item

- name: "teardown cfn stack resource def of current group"
  include: teardown_aws_cfn.yml res_def={{ res_item.0 }} res_grp_name={{ res_item.1 }}
  when: res_item.0['res_type'] == "aws_cfn"
  with_nested:
    - "{{ resource_definitions }}"
    - ["{{ res_grp['resource_group_name'] }}"]
  loop_control:
    loop_var: res_item
