sudo: false

# make ubuntu 16.04 the default version
dist: bionic

language: python

python:
  - "3.7"

cache: pip

install:
  - pip install -U setuptools
  - pip install -U pip
  - pip install .
  - pip install .[tests]

script:
  - flake8 --exclude=\.eggs,tests,docs,config/Dockerfiles --ignore=E124,E303,W504 --max-line-length 80 .
  - $(which python) setup.py test
  - egrep -c '(vmx|svm)' /proc/cpuinfo
  - sudo apt install cpu-checker
  - sudo kvm-ok
  - sudo apt update
  - sudo apt install qemu qemu-kvm libvirt-bin  bridge-utils  virt-manager
  - sudo service libvirtd start
