- name: "provision/deprovision the os volume resource type"
  os_volume:
    auth:
      auth_url: "{{ endpoint }}" 
      username: "{{ username }}"
      password: "{{ password }}"
      project_name: "{{ project }}" 
    state: "{{ state }}"
    size: "{{ res_def['size'] }}"
    display_name: "{{ res_def['res_name'] | default(res_def['name']) }}"
  when: res_def['count'] is not defined

- name: "Register resource count"
  shell: python -c "print [x for x in range( 0, {{ res_def['count'] }} )]"
  register: res_count
  when: res_def['count'] is defined

- name: "provision/deprovision cinder volumes when count specified"
  os_volume:
    auth:
      auth_url: "{{ vol.0 }}"
      username: "{{ vol.1 }}"
      password: "{{ vol.2 }}"
      project_name: "{{ vol.3 }}"
    state: "{{ vol.6 }}"
    size: "{{ vol.5 }}"
    display_name: "{{ vol.4 }}_{{ vol.7 }}"
  with_nested:
    - ["{{ endpoint }}"]
    - ["{{ username }}"]
    - ["{{ password }}"]
    - ["{{ project }}"]
    - ["{{ res_def['res_name'] | default(res_def['name']) }}"]
    - ["{{ res_def['size'] }}"]
    - ["{{ state }}"]
    - "{{ res_count.stdout }}"
  loop_control:
    loop_var: vol
  register: res_def_output 
  when: res_def['count'] is defined and async == false

- name: "Append outputitem to topology_outputs"
  set_fact:
    topology_outputs_os_volume: "{{ topology_outputs_os_volume + res_def_output.results }}"
  when: async == false


- name: "Async:: provision/deprovision cinder volumes when count specified"
  os_volume:
    auth:
      auth_url: "{{ vol.0 }}"
      username: "{{ vol.1 }}"
      password: "{{ vol.2 }}"
      project_name: "{{ vol.3 }}"
    state: "{{ vol.6 }}"
    size: "{{ vol.5 }}"
    display_name: "{{ vol.4 }}_{{ vol.7 }}"
  with_nested:
    - ["{{ endpoint }}"]
    - ["{{ username }}"]
    - ["{{ password }}"]
    - ["{{ project }}"]
    - ["{{ res_def['res_name'] | default(res_def['name']) }}"]
    - ["{{ res_def['size'] }}"]
    - ["{{ state }}"]
    - "{{ res_count.stdout }}"
  loop_control:
    loop_var: vol
  async: "{{ async_timeout }}"
  poll: 0
  register: res_def_output
  when: res_def['count'] is defined and async == true

#following tasks saves the async job details 
- name: "Async:: save the job id"
  set_fact:
    topology_outputs_os_volume: "{{ topology_outputs_os_volume + [ res_def_output ] }}"
  when: async == true
